// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6UUsC_oosvLBDVG-aX4YQDXvWOGpL50E',
    appId: '1:79570893103:web:f768f2eb8040e1168ac9da',
    messagingSenderId: '79570893103',
    projectId: 'match-app-47439',
    authDomain: 'match-app-47439.firebaseapp.com',
    storageBucket: 'match-app-47439.appspot.com',
    measurementId: 'G-9N1JW1H8WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFauosGm0ULUHO4gFZQFZO27J7ONVSPTU',
    appId: '1:79570893103:android:274f1a691d114f8b8ac9da',
    messagingSenderId: '79570893103',
    projectId: 'match-app-47439',
    storageBucket: 'match-app-47439.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjQ0YaJLJnVDifbJ2LJUHCQL2tnJjORJc',
    appId: '1:79570893103:ios:4f3dd307f6435b578ac9da',
    messagingSenderId: '79570893103',
    projectId: 'match-app-47439',
    storageBucket: 'match-app-47439.appspot.com',
    iosBundleId: 'com.example.fluuterDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjQ0YaJLJnVDifbJ2LJUHCQL2tnJjORJc',
    appId: '1:79570893103:ios:4f3dd307f6435b578ac9da',
    messagingSenderId: '79570893103',
    projectId: 'match-app-47439',
    storageBucket: 'match-app-47439.appspot.com',
    iosBundleId: 'com.example.fluuterDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6UUsC_oosvLBDVG-aX4YQDXvWOGpL50E',
    appId: '1:79570893103:web:607834c1ffaf42558ac9da',
    messagingSenderId: '79570893103',
    projectId: 'match-app-47439',
    authDomain: 'match-app-47439.firebaseapp.com',
    storageBucket: 'match-app-47439.appspot.com',
    measurementId: 'G-JJG04WLX0X',
  );

}